
/**
 * Card Payment class
 * 
 * A subclass of Payment. Stores a payment by credit card,
 * with the transaction reference number
 *
 * @author Katherine Wyers 
 * @version 1.0
 */
public class CardPayment extends Payment implements Referencable
{
    private final String referenceNumber;

    /**
     * Constructor for objects of class CardPayment
     * 
     * @param id int     
     * @param amount float
     * @param booking Booking
     * @param referenceNumber String
     */
    public CardPayment(int id, float amount, Booking booking, String referenceNumber)
    {
        super(id, amount, booking);
        this.referenceNumber = referenceNumber;
    }
    
    /**
     * getReferenceNumber
     * 
     * Get the payment reference number 
     * that was generated by the POS terminal 
     * where the credit-card payment was made
     * 
     * @return referenceNumber String
     */
    @Override
    public String getReferenceNumber()
    {
        return this.referenceNumber;
    }
}
